### PR TITLE
Update Blurred Poster Values

### LINKED ISSUE #99: Refine Game Logic
### Description

Currently, the game logic is pretty simple:
* an image of a movie poster is unblurred within 10 seconds
* the goal of the user is to guess the movie title
* if the user clicks the screen, he is presented with 4 options to choose from
* currently, the user can wait 10 seconds and red the movie title from the psoter (the title is usually displayed on the poster)
* it is therefore very easy to guess the correct movie title

### Tasks
- [x] Adjust blur to make it easier for the player to guess the poster within the first few seconds.

### Context 
#33

### PR DESCRIPTION
**Pull request by nikzaugg**
### Description

Make the unbluring of the poster start from a lower value to make it more interesting. Before, it was almost impossible to guess the movie poster within the first 5 seconds.

### Checklist

- [x] Have you added tests where necessary? Do all the test pass? 
- [x] Have you added descriptive comments to your code?
- [x] Have you updated the documentation related to this PR

### CODE REVIEW

**Review by rschlaefli — COMMENTED** [review]
@nikzaugg Don't we also want do set the toValue so something other than 0? To not end up with a totally unblurred poster.. E.g., from: 20px, to: 3px?

Or do you want to handle that differently, e.g., by redirecting before 0sec are reached?

**Comment by nikzaugg** [comment]
> @nikzaugg Don't we also want do set the toValue so something other than 0? To not end up with a totally unblurred poster.. E.g., from: 20px, to: 3px?
> 
> Or do you want to handle that differently, e.g., by redirecting before 0sec are reached?

@rschlaefli 
I am not sure. I think we discussed that we would leave it like it is right now for the time being, as the player still gets 50 points anyway if he/she waits for 10seconds. And we don't want to rebuild the scoring logic right now etc...

But yes, we could go from 15px to 3px to maybe make it more interesting. I will take a look at it again. Or what do you guys think? @alexscheitlin

**Comment by alexscheitlin** [comment]
> > @nikzaugg Don't we also want do set the toValue so something other than 0? To not end up with a totally unblurred poster.. E.g., from: 20px, to: 3px?
> > Or do you want to handle that differently, e.g., by redirecting before 0sec are reached?
> 
> @rschlaefli
> I am not sure. I think we discussed that we would leave it like it is right now for the time being, as the player still gets 50 points anyway if he/she waits for 10seconds. And we don't want to rebuild the scoring logic right now etc...
> 
> But yes, we could go from 15px to 3px to maybe make it more interesting. I will take a look at it again. Or what do you guys think? @alexscheitlin

I'm fine with leaving it as it is for now.

**Review by alexscheitlin — APPROVED** [review]

**Review by rschlaefli — APPROVED** [review]
OK

**Pull request merged**
