### PR TITLE
Add all pages and routing

### LINKED ISSUE #35: General Routing of Application
### Description

Add a Ionic Router to the application that has all required routes for the MVP.

### Tasks

- [x] add routes for all required screen for the MVP
- [x] add simple navigation between the screens with basic buttons/clicks

### PR DESCRIPTION
**Pull request by nikzaugg**
### Description

This PR adds the needed pages for the MVP and a basic router to display the corresponding page based on a route.

### Related Issues

Issue: #35 

### Checklist

- [x] Have you added tests where necessary? Do all the test pass? 
- [x] Have you added descriptive comments to your code?
- [x] Have you updated the documentation related to this propo

### CODE REVIEW

**Comment by nikzaugg** [comment]
I need to look into the clearing of the `setInterval` on the `Poster.tsx` page. It is currently not behaving as expected.

**Comment by nikzaugg** [comment]
FYI: Ionic provides their own Lifecycle hooks that we need to use. The usual hooks such as `useEffect` will not work.

See here: https://ionicframework.com/docs/react/lifecycle

**Comment by rschlaefli** [comment]
@nikzaugg Looks good, and good find with the Ionic hooks. However, when I run it through and get to a second question, the timer is (still) stuck at 0 instead of starting anew. Shouldn't that be fixed with these Ionic lifecycle hooks?

**Comment by nikzaugg** [comment]
Apparently not :-) 
I will look into it later.

**Comment by nikzaugg** [comment]
@rschlaefli I'm resetting the timer now inside the `useIonViewWillEnter` hook. Also I've gone ahead and created a `settings.ts` file, which we can use later on as the default values for the game's settings and to then adjust the "difficulty" and what not.

**Review by rschlaefli — APPROVED** [review]
Great!

**Pull request merged**
